spring.application.name=eureka-service
server.port=8081
eureka.client.service-url.defaultZone={EUREKA_URL:http://localhost:8081/eureka}
eureka.client.register-with-eureka=false
eureka.server.enable-self-preservation=false
eureka.client.fetch.registry=false