spring.application.name=eureka-service
server.port=8081
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8081/eureka}
eureka.client.register-with-eureka=false
eureka.server.enable-self-preservation=false
eureka.client.fetch.registry=false

# OBSERVABILITY
# traces
management.tracing.enabled=true
management.tracing.sampling.probability=1.0

# metrics
management.otlp.metrics.export.enabled=true 

# collector
management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics